# Define contactId for testing (change this ID as needed for different tests)
@contactId=6813de8ce4570a61ee70fa71
@renderUrl=https://cse341-tpkb.onrender.com
@localHost=http://localhost:8080
@testId=681d505f3aa759cc003003c5

### GET all contacts (local)
GET {{localHost}}/contacts

### GET all contacts (Render)
GET {{renderUrl}}/contacts

### GET contact by ID (local)
GET {{localHost}}/contacts/{{contactId}}

### GET contact by ID (Render)
GET {{renderUrl}}/contacts/{{contactId}}

### POST new contact (local)
POST {{localHost}}/contacts/
Content-Type: application/json

{
  "firstName": "New",
  "lastName": "Contact",
  "email": "newContact@example.com",
  "favoriteColor": "Yellow",
  "birthday": "01/01/2000"
}

### POST new contact (Render)
POST {{renderUrl}}/contacts
Content-Type: application/json

{
  "firstName": "New",
  "lastName": "Contact",
  "email": "newContact@example.com",
  "favoriteColor": "Yellow",
  "birthday": "01/01/2000"
}

### PUT update contact (local)
PUT {{localHost}}/contacts/{{testId}}
Content-Type: application/json

{
  "firstName": "Updated",
  "lastName": "Contact",
  "email": "updatedContact@example.com",
  "favoriteColor": "Purple",
  "birthday": "01/01/1111"
}


### PUT update contact (Render)
PUT {{renderUrl}}/contacts/{{testId}}
Content-Type: application/json

{
  "firstName": "Updated",
  "lastName": "Name",
  "email": "updatedemail@example.com",
  "favoriteColor": "Purple",
  "birthday": "01/01/1111"
}

### DELETE contact (local)
DELETE {{localHost}}/contacts/{{testId}}

### DELETE contact (Render)
DELETE {{renderUrl}}/contacts/{{testId}}
